# Use this for CentOS 7.x
# Run like this when SSH works with password only: $ ansible-playbook -i <IP>, test-hardening-role-centos --user=<connection-user> --ask-pass
# Run like this when SSH works with key (and ask for sudo password): $ ansible-playbook -i <IP>, test-hardening-role-centos --user=<connection-user> --become --ask-become-pass
---
- hosts: all

  vars:
    # add_deployment_user: False
    # enable_auto_update: False
    # enable_fail2ban: False
    # enable_ufw: False # error?
    public_keys: [
        '~/.ssh/id_rsa.pub',
      ]
    # password is `test`
    # deployment_password: $6$AC3bdCF7$MA5sPtsGsOei6fCtyyzHeOqBpEzsi.yl9wS1yaP1.nKhuNR6ZBmcouWh6XJkrFdzreENtvUF4Gr2R0gfIQ/PT.
    # enable_stop_password_authentication: False
    # enable_stop_root_login: False

  vars_prompt:
    - name: "deployment_password"
      prompt: "What password to use for new user?"
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes
      salt_size: 7

  roles:
  - {
      role: .,
    }
